# Generated by Django 2.0.7 on 2018-07-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedNumberPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('is_issued', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedTin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('tin', models.CharField(max_length=10)),
                ('tin_for', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(choices=[('New', 'New'), ('Renew', 'Renew')], max_length=10)),
                ('vehicle_type', models.CharField(max_length=150)),
                ('particulars', models.CharField(max_length=150)),
                ('amount', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChargesOthers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('local_government', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('bussiness_area', models.CharField(max_length=5)),
                ('institution', models.CharField(max_length=50)),
                ('bussiness_status', models.CharField(max_length=50)),
                ('bussiness_class', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=20)),
                ('bussiness_ownership_type', models.CharField(max_length=50)),
                ('jtb_tin', models.CharField(max_length=10)),
                ('bussiness_name', models.CharField(max_length=250)),
                ('bussiness_owner', models.CharField(max_length=250)),
                ('bussiness_address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('bussiness_size', models.CharField(max_length=50)),
                ('longtitude', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=10)),
                ('enumerator', models.CharField(max_length=50)),
                ('supervisor', models.CharField(max_length=50)),
                ('coordinator', models.CharField(max_length=50)),
                ('staff', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Others', 'Others')], max_length=15)),
                ('state', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=50)),
                ('employment_status', models.CharField(max_length=15)),
                ('work_place', models.CharField(max_length=250)),
                ('passport_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearnersPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('particulars', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalGovArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_government_name', models.CharField(max_length=50, unique=True)),
                ('local_government_code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_code', models.CharField(max_length=15)),
                ('mda_name', models.CharField(max_length=250)),
                ('eco_code', models.CharField(max_length=15)),
                ('group_title', models.CharField(max_length=250)),
                ('ipsas_code', models.CharField(max_length=15)),
                ('ipsas_title', models.CharField(max_length=250)),
                ('aprvd_18', models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MDAEbill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('reference_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=250)),
                ('revenue_item', models.CharField(max_length=250)),
                ('period', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('mda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.MDA')),
                ('tin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.AssignedTin')),
            ],
        ),
        migrations.CreateModel(
            name='MDAList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mda_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberPlate',
            fields=[
                ('registration_date', models.DateField(auto_now_add=True)),
                ('local_government', models.CharField(max_length=50)),
                ('number_plate', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('is_issued', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayeeTaxpayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=250)),
                ('total_gross_income', models.FloatField()),
                ('pension', models.BooleanField(default=False)),
                ('NHIS', models.FloatField()),
                ('NHF', models.BooleanField()),
                ('life_assurance', models.FloatField()),
                ('company_tin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.AssignedTin')),
            ],
        ),
        migrations.CreateModel(
            name='Revalidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('old_plate_number', models.CharField(max_length=8)),
                ('new_plate_number', models.CharField(max_length=8)),
                ('tin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.AssignedTin')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_code', models.CharField(max_length=15)),
                ('mda_name', models.CharField(max_length=250)),
                ('eco_code', models.CharField(max_length=15)),
                ('group_title', models.CharField(max_length=250)),
                ('ipsas_code', models.CharField(max_length=15)),
                ('ipsas_title', models.CharField(max_length=250)),
                ('aprvd_18', models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StateCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_expired', models.BooleanField(default=False)),
                ('transaction_code', models.CharField(max_length=15)),
                ('chassis_number', models.CharField(max_length=17)),
                ('particulars', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField(null=True)),
                ('transaction_type', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('tin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.AssignedTin')),
                ('transaction_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.Office')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=250)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(default='password', max_length=50)),
                ('access_level', models.CharField(choices=[('Super Administrator', 'Super Administrator'), ('TIN User', 'TIN User'), ('MLA User', 'MLA User'), ('MLA Administrator', 'MLA Administrator'), ('PAYEE User', 'PAYEE User'), ('DA User', 'DA User'), ('Store User', 'Store User')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_password_changed', models.BooleanField(default=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_owners_tin', models.CharField(max_length=10)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('chassis_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=8, unique=True)),
                ('vehicle_category', models.CharField(max_length=50)),
                ('gross_weight', models.IntegerField()),
                ('net_weight', models.IntegerField()),
                ('no_of_passengers', models.IntegerField()),
                ('colour', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('engine_size', models.CharField(max_length=15)),
                ('cost_price', models.CharField(max_length=50, null=True)),
                ('theft_status', models.BooleanField(default=False)),
                ('current_owner_tin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.AssignedTin')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.Office')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='transactionassessment',
            name='transaction_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.User'),
        ),
        migrations.AddField(
            model_name='payeetaxpayer',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.User'),
        ),
        migrations.AddField(
            model_name='numberplate',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.User'),
        ),
        migrations.AddField(
            model_name='learnerspermit',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.Office'),
        ),
        migrations.AddField(
            model_name='learnerspermit',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.User'),
        ),
        migrations.AddField(
            model_name='learnerspermit',
            name='tin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.AssignedTin'),
        ),
        migrations.AddField(
            model_name='individual',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.Office'),
        ),
        migrations.AddField(
            model_name='individual',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.User'),
        ),
        migrations.AddField(
            model_name='individual',
            name='tin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.AssignedTin'),
        ),
        migrations.AddField(
            model_name='company',
            name='institution_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.InstitutionCategory'),
        ),
        migrations.AddField(
            model_name='company',
            name='institution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.InstitutionType'),
        ),
        migrations.AddField(
            model_name='company',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.Office'),
        ),
        migrations.AddField(
            model_name='company',
            name='tin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.AssignedTin'),
        ),
        migrations.AddField(
            model_name='assignednumberplate',
            name='number_plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.NumberPlate'),
        ),
        migrations.AddField(
            model_name='assignednumberplate',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreIGR_app.Office'),
        ),
    ]
